### ISSUE TITLE
Responsive:  Tooltip is not responsive in certain breakpoints.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis-polar#1]
This is a responsive issue with the tooltip that opens on hover the data points.
Tooltip is not responsive in certain breaktpoint, e.g. ipad portrait.

Screenshot attached below:

![image](https://cloud.githubusercontent.com/assets/10835611/19452960/ee89b7f0-9467-11e6-9aa2-96b2bf347655.png)

**Comment by nonmetalhail** [comment]
Works on post DR site
