### ISSUE TITLE
px-vis-polar capability

### ISSUE THREAD

**Issue by rupeshpadhye** [PredixDev/px-vis-polar#3]
is px-vis-polar capable to plot graph for a time and amplitude

**Comment by nonmetalhail** [comment]
If your dataset has a phase, then yes. Otherwise, there is no way to relate an angle to your dataset.

**Comment by rupeshpadhye** [comment]
@nonmetalhail   As per our requirement we don't have phase . We need a polar graph showing amplitude in day/hour(time).
I think if we want achieve this we need to calculate angle from datetime.
Do you have any suggestion
 
Thanks for the quick response.

**Comment by benoitjchevalier** [comment]
In theory you could by doing heavy data manipulation, i.e converting your time range to a 0-360 angle range. You will also be able to change the angle labels on the chart. However the chart hasn't been built with this purpose in mind so I can't guarantee you won't run into other issues...

Nonetheless I think we have had an ask and actually prioritized this feature for the next quarter, so depending on your timeframe you might want to hold on

**Comment by rupeshpadhye** [comment]
@benoitjchevalier  thanks for the update,We are actually planning this feature in this quarter. This is one of the must have in MVP
