### ISSUE TITLE
How to link px-vis-navigator with px-vis-polar?

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-vis-polar#4]
In time series Px-vis-navigator is an inbuilt functionality with the time series( ), however in px-vis-polar, navigator and chart are not combined. Could you please let me know how to link both the px-vis-navigator and px-vis-polar?

**Comment by benoitjchevalier** [comment]
Hello,

you can have a look at the demo site (https://www.predix-ui.com/#/components/px-vis-polar/) or the index.html/dev.html files in the polar repo.

**Comment by anundinesh** [comment]
thanks! time-domain(px-vis-polar) and selected-domain(px-vis-navigator) are mandatory to have, in order to get navigator and polar to get it work? what exact data will be their in time-domain and selected-domain?

**Comment by anundinesh** [comment]
We have figured a way to bind it.
