### ISSUE TITLE
horizontal alignment crates respected results

### ISSUE THREAD

**Issue by vonsichart200** [PredixDev/px-vis-polar#6]
**Safari 10:**
Right alignment moves the chart to the left and vice versa.

**Firefox 54:**
Horizontal alignment has no effect

![screen shot 2017-08-04 at 10 34 08 am](https://user-images.githubusercontent.com/25111262/28979895-85a948f8-7900-11e7-970f-8f838d38f4b5.png)

**Comment by nonmetalhail** [comment]
I'm very glad you respect our results :)

**Comment by nonmetalhail** [comment]
Cannot reproduce either issue...
