### ISSUE TITLE
Firefox: warning when hovering over the zero axis

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-vis-polar#7]
Getting a warning from d3 when hovering over the 0 axis with all the default properties intact on the demo page.

Only happens in FF, none of the other browsers generate a warning...
![28800761-ff68136e-7602-11e7-929c-35988081ac2d](https://user-images.githubusercontent.com/2130613/29290115-cb2284a8-80f3-11e7-9019-8066a994ca6b.png)

**Comment by nonmetalhail** [comment]
Fix will be in zoom enhancement release
